apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-ingress
  namespace: default
  annotations:
    konghq.com/plugins: opa-authz
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /catalog
        pathType: Prefix
        backend:
          service:
            name: mock-catalog
            port:
              number: 8000
            